### ISSUE TITLE
Multisite Install - Super Admins Forced to Re-authenticate for Every Child Site on Network

### ISSUE THREAD

**Issue by JackieKrkwd** [duosecurity/duo_universal_wordpress#61]
On a Multisite install, once logged into the main site as a Super Admin when you to navigate to a child site's dashboard you are asked to log in and authenticate with Duo again. If you don't log in and navigate back to the main site's dashboard you are asked to log in and re-authenticate again on the main site. It seems like the login credentials aren't persisting across the Multisite Network.

Super Admins are usually developers or webmasters and make multiple changes to all child sites. This would cut down on the amount of logins a Super Admin needs to make just completing everyday tasks. I believe that the previous Duo plugin allowed for this functionality.

Allow Multisite Super Admins the right to log into the main site and navigate to the dashboards of child sites without re-authentication on each child site. WordPress core allows this functionality for Super Admins already.

Super Admin logins are not persisting across Multisite Network.

## Steps to Reproduce
1. login to Multisite through /wp-admin/ on the main site
2. navigate to a child site's dashboard (you will be asked to log in and re-authenticate)
3.  if you do not log in and re-authenticate go back to main site's /wp-admin/
4. you will be asked to log in and re-authenticate on the main site again

## Workarounds
I have not found a workaround.

**Comment by michael-sumner** [comment]
@JackieKrkwd thank you for raising this. We are also experiencing the same issue.

Could you let us know if you are still having the issue, or if you found a workaround for it?

**Comment by JackieKrkwd** [comment]
We are still experiencing this issue. I have not yet found a workaround. The best I've been able to do to avoid logging in and getting kicked out multiple times is log in and authenticate to all child sites in different tabs so it keeps me signed in and I can navigate the network without getting logged out.

**Comment by michael-sumner** [comment]
Thanks @JackieKrkwd - we might use that solution for the time being. Do you know if you are on a clustered hosting environment (for example, Kubernetes) or if you have multiple db's or that the codebase regenerates itself (for example, Pantheon's / WP VIP / WP Engine / etc. hosting environment)?

**Comment by jeffreyparker** [comment]
Thanks for filing this issue! We're investigating this but have been unable to reproduce it in our local testing, so it may be environment / hosting-provider specific. Would you be able to provide details as to the provider and the specific version of Wordpress? You can also open a case with Duo Support to send these details privately. Thanks!

**Comment by JackieKrkwd** [comment]
@jeffreyparker I am also experiencing this issue in my local development environment, but I will email support with more details.

**Comment by JackieKrkwd** [comment]
@jeffreyparker We've been emailing back and forth with Duo support and aren't getting anywhere. Is there a more direct email for support for this plugin where we could provide the information you asked for?

This is the last response we got:

If you see an issue again where Duo is prompting more often than you expect, please keep in mind that Duo does not create authentication events, it will prompt for a Duo push every time it receives an authentication event from the protected application. When this happens, we suggest looking at the application logs first to find out why multiple authentication events take place.

Having said that, if you think there is a Duo related issue, please let us know and we are happy to investigate further.

I tried to explain that we were trying to contact Duo support about the Duo Universal WordPress Plugin, not Duo authentication itself, but I don't think they understand the request.

**Comment by jeffreyparker** [comment]
@JackieKrkwd On no I'm sorry to hear that! If you could let me know the support ticket number here, I can follow up with them to ensure it's properly routed.

**Comment by JackieKrkwd** [comment]
@jeffreyparker Thank you for your response. The ticket number is Duo Support ticket 01496661.

**Comment by jeffreyparker** [comment]
@JackieKrkwd Great! I've found your case and have enough information to continue trying to track down this issue for now. We'll be in touch (either here or via the support case) if we need any further information. Thank you!

**Comment by jeffreyparker** [comment]
@JackieKrkwd , @michael-sumner . Version 1.1.0 of the plugin was just released which includes a fix for this issue. Please let us know if you still encounter this after updating. Thank you!

**Comment by JackieKrkwd** [comment]
@jeffreyparker Thank you! I just tested it and it seems to be working as expected!

**Comment by jeffreyparker** [comment]
Wonderful! Thank you for the confirmation and thank you again for providing all of the info needed to help us address this issue!
